services:
  postgresql:
    image: bitnami/postgresql:16
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: postgres
    ports:
      - 5432:5432
